import { reactive, ref } from 'vue';
import type { SizeMeasurementEntry, SizeMeasurementSpec } from '../../../utils/sizeMeasurements';
import { findMeasurementForSize, findSpecEntry, findSpecValueInInches, normalizeSizeLabel } from '../../../utils/sizeMeasurements';

export type View = 'Front' | 'Back';

export type DesignGrid = {
  x: number;
  y: number;
  w: number;
  h: number;
  widthInches?: number | null;
  heightInches?: number | null;
  dpi?: number | null;
  auto?: boolean | null;
  autoGenerated?: boolean | null;
};

export interface DetectionMetrics {
  garmentWidthPx: number;
  garmentHeightPx: number;
  gridWidthPx: number;
  gridHeightPx: number;
}

const DEFAULT_DETECTION_METRICS: DetectionMetrics = {
  garmentWidthPx: 0,
  garmentHeightPx: 0,
  gridWidthPx: 0,
  gridHeightPx: 0,
};

const ENABLE_AUTO_GRID = true;

const DEFAULT_CLOTHING_DETAILS = () => ({
  name: '',
  image: '',
  grid: {} as DesignGrid,
  style: '',
  gender: '',
  size: '',
  sizeMeasurements: [] as SizeMeasurementEntry[],
});

function numeric(val: any | null | undefined): number | undefined {
  const num = Number(val);
  return Number.isFinite(num) ? num : undefined;
}

function parseMeasurementValue(raw: unknown): number | null {
  if (typeof raw === 'number') {
    return Number.isFinite(raw) ? raw : null;
  }
  if (typeof raw !== 'string') return null;
  let cleaned = raw.trim();
  if (!cleaned) return null;
  cleaned = cleaned.replace(/["”]/g, '');
  cleaned = cleaned.replace(/\b(?:inches?|inch|in)\.?$/i, '').trim();
  cleaned = cleaned.replace(/-/g, ' ');
  const decimalMatch = cleaned.match(/^([+-]?\d+(?:\.\d+)?)$/);
  if (decimalMatch) {
    return Number.parseFloat(decimalMatch[1]);
  }
  const mixedMatch = cleaned.match(/^([+-]?\d+)\s+(\d+)\/(\d+)$/);
  if (mixedMatch) {
    const whole = Number.parseInt(mixedMatch[1], 10);
    const numerator = Number.parseInt(mixedMatch[2], 10);
    const denominator = Number.parseInt(mixedMatch[3], 10);
    if (denominator === 0) return null;
    const fraction = numerator / denominator;
    return whole >= 0 ? whole + fraction : whole - fraction;
  }
  const fractionMatch = cleaned.match(/^([+-]?)(\d+)\/(\d+)$/);
  if (fractionMatch) {
    const sign = fractionMatch[1] === '-' ? -1 : 1;
    const numerator = Number.parseInt(fractionMatch[2], 10);
    const denominator = Number.parseInt(fractionMatch[3], 10);
    if (denominator === 0) return null;
    return sign * (numerator / denominator);
  }
  const fallback = Number(cleaned.replace(/[^0-9.+-]/g, ''));
  return Number.isFinite(fallback) ? fallback : null;
}

export function hydrateSizeMeasurements(value: any): SizeMeasurementEntry[] {
  let source: any[] = [];
  if (Array.isArray(value)) {
    source = value;
  } else if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      if (Array.isArray(parsed)) source = parsed;
    } catch {
      source = [];
    }
  }

  const normalized: SizeMeasurementEntry[] = [];
  for (const entry of source) {
    const sizeLabel = typeof entry?.sizeLabel === 'string'
      ? entry.sizeLabel.trim()
      : typeof entry?.label === 'string'
        ? entry.label.trim()
        : '';
    if (!sizeLabel) continue;

    const normalizedLabel = typeof entry?.normalizedLabel === 'string' && entry.normalizedLabel.trim()
      ? normalizeSizeLabel(entry.normalizedLabel)
      : normalizeSizeLabel(sizeLabel);

    const specsRaw = Array.isArray(entry?.specs) ? entry.specs : [];
    const specs: SizeMeasurementSpec[] = [];
    for (const spec of specsRaw) {
      const rawKey = typeof spec?.key === 'string' && spec.key.trim()
        ? spec.key.trim()
        : typeof spec?.type === 'string'
          ? spec.type.trim()
          : '';
      const key = rawKey.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      if (!key) continue;

      const type = typeof spec?.type === 'string' && spec.type.trim() ? spec.type.trim() : rawKey || key;
      const unit = typeof spec?.unit === 'string' && spec.unit.trim() ? spec.unit.trim() : 'inches';
      const rawValue = (spec as any)?.value ?? (spec as any)?.measurementValue ?? (spec as any)?.valueInInches ?? (spec as any)?.value_in_inches;
      const parsedValue = parseMeasurementValue(rawValue);
      if (!Number.isFinite(parsedValue)) continue;
      const rawValueInInches = Number((spec as any)?.valueInInches ?? (spec as any)?.value_in_inches);
      const valueInInches = Number.isFinite(rawValueInInches) ? rawValueInInches : null;

      specs.push({
        key,
        type,
        unit,
        value: parsedValue!,
        valueInInches: valueInInches ?? parsedValue! ?? null,
      });
    }

    normalized.push({ sizeLabel, normalizedLabel, specs });
  }

  return normalized;
}

export function createGridState(defaultGrid: DesignGrid) {
  const showGrid = ref(true);
  const clothingDetails = ref(DEFAULT_CLOTHING_DETAILS());
  clothingDetails.value.grid = { ...defaultGrid };

  const lastDetectionMetrics = reactive({ ...DEFAULT_DETECTION_METRICS });

  function resolveGrid(): DesignGrid {
    const grid = clothingDetails.value.grid as DesignGrid | undefined;
    return { ...defaultGrid, ...(grid || {}) };
  }

  function markGridManual() {
    clothingDetails.value.grid.auto = false;
    clothingDetails.value.grid.autoGenerated = false;
  }

  function shouldAutoDetect(grid: DesignGrid | null | undefined = clothingDetails.value.grid as DesignGrid) {
    if (!ENABLE_AUTO_GRID) return false;
    if (!grid) return true;
    if (grid.auto === false || grid.autoGenerated === false) return false;
    return true;
  }

  function getSizeMeasurements(): SizeMeasurementEntry[] {
    const entries = (clothingDetails.value as any).sizeMeasurements;
    if (Array.isArray(entries)) return entries as SizeMeasurementEntry[];
    return [];
  }

  function getActiveSizeMeasurement(): SizeMeasurementEntry | undefined {
    const entries = getSizeMeasurements();
    if (!entries.length) return undefined;
    const activeSize = (clothingDetails.value as any).size;
    return findMeasurementForSize(entries, typeof activeSize === 'string' ? activeSize : undefined);
  }

  const WIDTH_SPEC_KEYS = [
    'chest',
    'chest_width',
    'body_width',
    'width',
    'half_chest',
    'chest_circumference',
    'chest_girth',
    'body_circumference',
    'body_girth',
    'full_chest',
  ];

  function shouldTreatAsCircumference(
    spec: SizeMeasurementSpec | undefined,
    inches: number | undefined,
  ): boolean {
    if (!spec) return false;
    if (!Number.isFinite(inches)) return false;
    const normalizedKey = (spec.key ?? '').toLowerCase();
    const text = `${spec.type ?? ''} ${spec.key ?? ''} ${spec.unit ?? ''}`.toLowerCase();
    const circKeyword = /(circumference|girth|around|perimeter|sweep)/;
    const halfKeyword = /(half|1\/2|across|flat)/;
    const hasCircInKey = circKeyword.test(normalizedKey);
    const hasCircInText = circKeyword.test(text);
    const hasHalfHint = halfKeyword.test(text);
    if (hasCircInKey && !hasHalfHint) return true;
    if (!text.trim()) return false;
    if (hasHalfHint) return false;
    if (hasCircInText) return true;
    if (/(full|whole)/.test(text) && /(chest|bust|body)/.test(text)) return true;
    return false;
  }

  function normalizeWidthInches(
    spec: SizeMeasurementSpec | undefined,
    inches: number | undefined,
  ): number | undefined {
    if (!Number.isFinite(inches)) return inches;
    if (!spec) return inches;
    const value = inches as number;
    if (shouldTreatAsCircumference(spec, value)) {
      return Number((value / 2).toFixed(2));
    }
    return value;
  }

  function applyMeasurementsToGridFromCurrent(): boolean {
    if (!ENABLE_AUTO_GRID) return false;
    const measurement = getActiveSizeMeasurement();
    if (!measurement) return false;

    const garmentWidth = lastDetectionMetrics.garmentWidthPx;
    const garmentHeight = lastDetectionMetrics.garmentHeightPx;
    const gridWidth = lastDetectionMetrics.gridWidthPx;
    const gridHeight = lastDetectionMetrics.gridHeightPx;

    if (!garmentWidth || !garmentHeight || !gridWidth || !gridHeight) return false;

    const grid = clothingDetails.value.grid;

    const chestSpec = findSpecEntry(measurement, WIDTH_SPEC_KEYS);
    const chestRaw = typeof chestSpec?.valueInInches === 'number' && Number.isFinite(chestSpec.valueInInches)
      ? chestSpec.valueInInches
      : chestSpec?.value;
    const chestInches = normalizeWidthInches(chestSpec, chestRaw);
    const lengthInches = findSpecValueInInches(measurement, ['length', 'body_length', 'center_front_body_length']);

    let updated = false;

    if (chestInches && chestInches > 0) {
      const widthInches = Number((chestInches * (gridWidth / garmentWidth)).toFixed(2));
      if (Number.isFinite(widthInches) && widthInches > 0) {
        clothingDetails.value.grid.widthInches = widthInches;
        updated = true;
      }
    }

    if (lengthInches && lengthInches > 0) {
      const heightInches = Number((lengthInches * (gridHeight / garmentHeight)).toFixed(2));
      if (Number.isFinite(heightInches) && heightInches > 0) {
        clothingDetails.value.grid.heightInches = heightInches;
        updated = true;
      }
    }

    if (updated) {
      const ratios: number[] = [];
      if (clothingDetails.value.grid.widthInches && clothingDetails.value.grid.widthInches > 0 && grid.w > 0) {
        ratios.push(grid.w / clothingDetails.value.grid.widthInches);
      }
      if (clothingDetails.value.grid.heightInches && clothingDetails.value.grid.heightInches > 0 && grid.h > 0) {
        ratios.push(grid.h / clothingDetails.value.grid.heightInches);
      }
      if (ratios.length) {
        const avg = ratios.reduce((acc, val) => acc + val, 0) / ratios.length;
        clothingDetails.value.grid.dpi = Number(avg.toFixed(2));
      }
      clothingDetails.value.grid.auto = true;
      clothingDetails.value.grid.autoGenerated = true;
    }

    return updated;
  }

  function requestMeasurementRefresh() {
    if (!ENABLE_AUTO_GRID) return;
    applyMeasurementsToGridFromCurrent();
  }

  const DEFAULT_INCH_PX = 40;

  function getPixelsPerInch(): number {
    const grid = resolveGrid();

    const explicitDpi = numeric((grid as any).pxPerInch ?? (grid as any).pixelsPerInch ?? grid.dpi);
    if (explicitDpi && explicitDpi > 0) return explicitDpi;

    const widthInches = numeric((grid as any).widthInches ?? (grid as any).physicalWidth ?? (grid as any).widthIn ?? (grid as any).width_in);
    const heightInches = numeric((grid as any).heightInches ?? (grid as any).physicalHeight ?? (grid as any).heightIn ?? (grid as any).height_in);

    const ratios: number[] = [];
    if (widthInches && widthInches > 0 && grid.w > 0) ratios.push(grid.w / widthInches);
    if (heightInches && heightInches > 0 && grid.h > 0) ratios.push(grid.h / heightInches);

    if (ratios.length) {
      return ratios.reduce((acc, val) => acc + val, 0) / ratios.length;
    }

    return DEFAULT_INCH_PX;
  }

  function resetClothingDetails() {
    clothingDetails.value = DEFAULT_CLOTHING_DETAILS();
    clothingDetails.value.grid = { ...defaultGrid };
  }

  return {
    showGrid,
    clothingDetails,
    lastDetectionMetrics,
    resolveGrid,
    markGridManual,
    shouldAutoDetect,
    requestMeasurementRefresh,
    getPixelsPerInch,
    resetClothingDetails,
  };
}
