<template>
  <div class="page">
    <div class="lab-container" style="position:relative;">
      <input ref="fileInput" type="file" accept="image/*" multiple @change="onFileChange" style="display:none;" />

      <canvas ref="canvas" :width="canvasWidth" :height="canvasHeight" style="display:block;"
        :style="{ cursor: canvasCursor }" @mousedown="startDrag" @mousemove="onMove" @mouseup="stopDrag" />
      <!-- Vue icon handles for selected image -->
      <div v-if="selectedObject && selectedObject.type === 'image'">
        <div class="canvas" v-for="(handle, index) in ['delete', 'resize', 'duplicate', 'rotate']" :key="handle" :style="{
          left: getHandlePosition(index).x + 'px',
          top: getHandlePosition(index).y + 'px',
          cursor: index === 1 ? 'nesw-resize' : 'pointer',
          pointerEvents: (selectedObject && selectedObject.type === 'image') ? 'auto' : 'none'
        }" @click="handleImageClick(index)" @mousedown="handleMouseDown(index, $event)" @mouseup="stopDrag">
          <component :is="iconComponents[index]" />
        </div>
      </div>
      <div v-if="selectedObject && selectedObject.type === 'text' && selectedObject.showHandles === true">
        <!-- Delete: top-left -->
        <div class="canvas" :style="{
          left: getTextHandlePosition('topLeft').left + 'px',
          top: getTextHandlePosition('topLeft').top + 'px',
          cursor: 'pointer',
          pointerEvents: 'auto'
        }" @click="handleTextClick(0)">
          <component :is="iconComponents[0]" />
        </div>

        <!-- Bottom-right handles -->
        <div class="canvas" v-for="(btnIndex, i) in [1, 2, 3]" :key="i" :style="{
          left: getTextHandlePosition('bottomRight').left - 32 * i + 'px', // 1rem = 16px
          top: getTextHandlePosition('bottomRight').top + 'px',
          cursor: i === 0 ? 'ew-resize' : 'pointer'
        }" @mousedown="i === 0 ? handleTextMouseDown(1, $event) : null"
          @click="btnIndex !== 1 ? handleTextClick(btnIndex) : null">
          <component :is="textIconComponents[btnIndex]" />
        </div>
      </div>
    </div>
    <div class="sidebar">
      <div class="viewport-frame">
        <ViewPort label="Front" :is-active="selectedView === 'Front'"
          :preview-src="frontPreview || viewToSrc.Front || fallbackPreview" @select="handleViewSelect" />
        <ViewPort label="Back" :is-active="selectedView === 'Back'"
          :preview-src="backPreview || viewToSrc.Back || viewToSrc.Front || fallbackPreview"
          @select="handleViewSelect" />
      </div>

      <input type="button" @click="showGrid = !showGrid" :value="showGrid ? 'Hide Grid' : 'Show Grid'" />

    </div>

  </div>
</template>

<script setup lang="ts">
  import { onMounted, onUnmounted, watch, ref, reactive } from 'vue';

  import DeleteIcon from 'vue-material-design-icons/Close.vue'
  import DuplicateIcon from 'vue-material-design-icons/ContentDuplicate.vue'
  import ResizeIcon from 'vue-material-design-icons/CropFree.vue'
  import ArrowLeftRight from 'vue-material-design-icons/ArrowLeftRight.vue'
  import RotateIcon from 'vue-material-design-icons/RotateRight.vue'
  import ViewPort from '../../components/shirtlab/Viewports/ViewPort.vue';
  import type { TextObject, ImageObject } from './types'
  // ADD with the other imports
  import { withDefaults, getEffectTransform, getEffectAdvance, applyToContext } from '../sideMenu/types/effectsList';
  import { getAABB, getAABBCorners, getRotatedCorners, pointInRotatedRect } from './utils/geometry';
  import { useDesignLayers } from './composables/useDesignLayers';
  import { createGridState, hydrateSizeMeasurements, type DesignGrid, type View } from './composables/useGrid';

  const props = defineProps<{
    clothing?: {
      name?: string;
      front?: string;    // URL for front garment image
      back?: string;     // URL for back garment image
      side?: string;     // URL for sleeve/side garment image
      grid?: {
        x: number;
        y: number;
        w: number;
        h: number;
        widthInches?: number;
        heightInches?: number;
        dpi?: number;
        pxPerInch?: number;
        pixelsPerInch?: number;
        auto?: boolean;
        autoGenerated?: boolean;
      };
      colors?: Array<{ background?: string; sideUrl?: string; side?: string }>; // legacy fallback
    }
  }>();




  import Zoom from './image.png'
  // Icon component array for handle buttons
  const iconComponents = [DeleteIcon, ResizeIcon, DuplicateIcon, RotateIcon];
  const textIconComponents = [DeleteIcon, ArrowLeftRight, DuplicateIcon, RotateIcon];
  const fallbackPreview = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';

  // -----------------------------------------------------
  // Reactive State & Composables
  // -----------------------------------------------------

  /**
   * Runtime bookkeeping for drag/resize interactions across canvas object types.
   */
  const dragState = reactive({
    text: {
      isResizing: false,
      index: -1,
      offset: { x: 0, y: 0 },
    },
    image: {
      index: -1,
      resizeHandle: -1,
      resizingIndex: -1,
      offset: { x: 0, y: 0 },
    },
    guide: {
      isDragging: false,
      handle: -1,
      offset: { x: 0, y: 0 },
    },
  });


  // at top-level (script setup)
  let onWinMove: ((e: MouseEvent) => void) | null = null;
  let onWinUp: ((e: MouseEvent) => void) | null = null;

  /**
   * Begins resizing a text object by wiring global mouse listeners to the drag loop.
   */
  function handleTextMouseDown(index: number, event: MouseEvent) {
    event.preventDefault();
    if (index !== 1) return; // only BR resize
    if (!selectedObject.value || selectedObject.value.type !== 'text') return;

    dragState.text.isResizing = true;
    mouseDown.value = true;

    // global listeners so drag works even though we started on a DOM handle
    onWinMove = (e) => onDrag(e as unknown as MouseEvent);
    onWinUp = () => stopDrag();

    window.addEventListener('mousemove', onWinMove);
    window.addEventListener('mouseup', onWinUp);
  }

  /**
   * Samples the garment edges to approximate its dominant background colour.
   */
  function estimateBackgroundColor(data: Uint8ClampedArray, width: number, height: number) {
    const samples = [
      [0, 0],
      [width - 1, 0],
      [0, height - 1],
      [width - 1, height - 1],
      [Math.floor(width * 0.5), 0],
      [Math.floor(width * 0.5), height - 1],
      [0, Math.floor(height * 0.5)],
      [width - 1, Math.floor(height * 0.5)],
    ];
    let r = 0, g = 0, b = 0, count = 0;
    for (const [x, y] of samples) {
      const idx = (y * width + x) * 4;
      const alpha = data[idx + 3];
      if (alpha < 10) continue;
      r += data[idx];
      g += data[idx + 1];
      b += data[idx + 2];
      count += 1;
    }
    if (!count) return null;
    return { r: r / count, g: g / count, b: b / count };
  }

  /**
   * Detects a printable grid from the garment image and updates measurements accordingly.
   */
  function autoFitGridFromBackground() {
    if (!shirtBgLoaded.value) return;
    const iw = (shirtBg as any).naturalWidth || shirtBg.width;
    const ih = (shirtBg as any).naturalHeight || shirtBg.height;
    if (!iw || !ih) return;

    const offscreen = document.createElement('canvas');
    offscreen.width = iw;
    offscreen.height = ih;
    const offCtx = offscreen.getContext('2d', { willReadFrequently: true });
    if (!offCtx) return;

    try {
      offCtx.drawImage(shirtBg, 0, 0, iw, ih);
    } catch (err) {
      console.warn('[ShirtPlacer] Failed to draw shirt image for auto grid', err);
      return;
    }

    let imageData: ImageData;
    try {
      imageData = offCtx.getImageData(0, 0, iw, ih);
    } catch (err) {
      console.warn('[ShirtPlacer] Unable to read pixel data for auto grid (likely cross-origin)', err);
      return;
    }

    const background = estimateBackgroundColor(imageData.data, iw, ih);
    if (!background) return;

    const step = Math.max(1, Math.floor(Math.min(iw, ih) / 600));
    const threshold = 45;

    let minX = iw, maxX = -1, minY = ih, maxY = -1;
    const rowEdges: Array<{ y: number; left: number; right: number }> = [];

    for (let y = 0; y < ih; y += step) {
      let rowLeft = iw;
      let rowRight = -1;
      for (let x = 0; x < iw; x += step) {
        const idx = (y * iw + x) * 4;
        const alpha = imageData.data[idx + 3];
        if (alpha < 32) continue;
        const diff = Math.abs(imageData.data[idx] - background.r)
          + Math.abs(imageData.data[idx + 1] - background.g)
          + Math.abs(imageData.data[idx + 2] - background.b);
        if (diff > threshold) {
          if (x < minX) minX = x;
          if (x > maxX) maxX = x;
          if (y < minY) minY = y;
          if (y > maxY) maxY = y;
          if (x < rowLeft) rowLeft = x;
          if (x > rowRight) rowRight = x;
        }
      }
      if (rowRight >= rowLeft && rowRight !== -1) {
        rowEdges.push({ y, left: rowLeft, right: rowRight });
      }
    }

    if (maxX <= minX || maxY <= minY) {
      console.warn('[ShirtPlacer] auto grid detection failed: could not detect garment bounds');
      return;
    }

    const height = maxY - minY;
    const torsoRows = rowEdges.filter(row => row.y >= minY + height * 0.35 && row.y <= minY + height * 0.75);
    let torsoLeft = minX;
    let torsoRight = maxX;
    if (torsoRows.length) {
      torsoLeft = torsoRows.reduce((sum, row) => sum + row.left, 0) / torsoRows.length;
      torsoRight = torsoRows.reduce((sum, row) => sum + row.right, 0) / torsoRows.length;
    }

    const torsoWidth = Math.max(1, torsoRight - torsoLeft);
    const sideInset = torsoWidth * 0.08;
    const gridLeft = Math.max(minX, torsoLeft + sideInset);
    const gridRight = Math.min(maxX, torsoRight - sideInset);

    const topInset = height * 0.1;
    const bottomInset = height * 0.07;
    const gridTop = minY + topInset;
    const gridBottom = maxY - bottomInset;

    if (gridRight <= gridLeft || gridBottom <= gridTop) {
      console.warn('[ShirtPlacer] auto grid detection produced invalid bounds');
      return;
    }

    lastDetectionMetrics.garmentWidthPx = Math.max(0, torsoRight - torsoLeft);
    lastDetectionMetrics.garmentHeightPx = Math.max(0, maxY - minY);
    lastDetectionMetrics.gridWidthPx = Math.max(0, gridRight - gridLeft);
    lastDetectionMetrics.gridHeightPx = Math.max(0, gridBottom - gridTop);

    const { scale, offsetX, offsetY } = computeShirtTransform(iw, ih);
    const canvasLeft = offsetX + gridLeft * scale;
    const canvasTop = offsetY + gridTop * scale;
    let canvasWidthPx = (gridRight - gridLeft) * scale;
    let canvasHeightPx = (gridBottom - gridTop) * scale;

    const clamp = (val: number, min: number, max: number) => Math.min(Math.max(val, min), max);
    const clampedLeft = clamp(canvasLeft, 0, canvasWidth - 50);
    const clampedTop = clamp(canvasTop, 0, canvasHeight - 50);
    canvasWidthPx = Math.max(60, Math.min(canvasWidthPx, canvasWidth - clampedLeft));
    canvasHeightPx = Math.max(60, Math.min(canvasHeightPx, canvasHeight - clampedTop));

    const widthInches = clothingDetails.value.grid.widthInches ?? 12;
    const heightInches = clothingDetails.value.grid.heightInches
      ?? Number((widthInches * (canvasHeightPx / Math.max(canvasWidthPx, 1))).toFixed(2));

    clothingDetails.value.grid = {
      ...resolveGrid(),
      x: clampedLeft,
      y: clampedTop,
      w: canvasWidthPx,
      h: canvasHeightPx,
      widthInches,
      heightInches,
      autoGenerated: true,
      auto: true,
    } as DesignGrid & Record<string, any>;

    requestMeasurementRefresh();

    cancelAutoGridMeasurement();
    draw();
  }

  /**
   * Computes the visual handle position for a selected text block.
   */
  function getTextHandlePosition(pos: 'topLeft' | 'bottomRight') {
    const t = selectedObject.value as TextObject;
    const ctx = canvas.value?.getContext('2d');
    if (!t || !ctx) return { top: 0, left: 0 };

    const block = layoutTextBlock(ctx, t);
    const topLeft = { top: block.boundsTop, left: block.boundsLeft };
    const bottomRight = { top: block.boundsTop + block.height, left: block.boundsLeft + block.width };
    const bottomLeft = { top: block.boundsTop + block.height, left: block.boundsLeft };
    const bottomCenter = { top: block.boundsTop + block.height, left: block.boundsLeft + block.width / 2 };

    if (pos === 'topLeft') return topLeft;
    if (pos === 'bottomRight') {
      // Move the resize handle depending on alignment
      if (t.alignment === 'right') return bottomLeft;    // left side for right alignment
      if (t.alignment === 'center') return bottomCenter; // centered for center alignment
      return bottomRight;                                 // right side for left alignment
    }
    return { top: 0, left: 0 };
  }

  /**
   * Executes selected text toolbar actions like delete, duplicate, or rotate.
   */
  function handleTextClick(index: number) {
    const t = selectedObject.value as TextObject;
    if (!t) return;
    switch (index) {
      case 0: // delete
        texts.splice(texts.findIndex(x => x.isSelected), 1);
        selectedObject.value = null
        break;
      case 2: // duplicate
        deselectAll()
        const clone = { ...t, id: crypto.randomUUID?.() || Date.now().toString() };
        clone.x += 20; clone.y += 20;
        clone.isSelected = true
        texts.push(clone);
        selectedObject.value = clone
        break;
      case 3: // rotate
        t.rotation = (t.rotation + 15) % 360;

        break;
    }
    draw();
  }

  const {
    images,
    texts,
    selectedObject,
    zCounter,
    getAllObjectsByZ,
    rebalanceZ,
    getZExtrema,
    deselectAll,
  } = useDesignLayers();
  // Translate item so its rotated AABB stays fully inside the grid
  function clampIntoGrid(item: { x: number; y: number; w: number; h: number; rotation?: number }) {
    const grid = resolveGrid();
    const a = getAABB(item);
    let dx = 0, dy = 0;
    if (a.minX < grid.x) dx = grid.x - a.minX;
    if (a.maxX > grid.x + grid.w) dx = Math.min(dx, (grid.x + grid.w) - a.maxX);
    if (a.minY < grid.y) dy = grid.y - a.minY;
    if (a.maxY > grid.y + grid.h) dy = Math.min(dy, (grid.y + grid.h) - a.maxY);
    if (dx !== 0 || dy !== 0) {
      item.x += dx;
      item.y += dy;
    }
  }



  function getHandlePosition(index: number) {
    const img = selectedObject.value as ImageObject;
    if (!img) return { x: 0, y: 0 };
    const a = getAABBCorners(img);
    switch (index) {
      case 0: return { x: a.TL.x, y: a.TL.y }; // TL (delete)
      case 1: return { x: a.TR.x, y: a.TR.y }; // TR (resize)
      case 2: return { x: a.BL.x, y: a.BL.y }; // BL (duplicate)
      case 3: return { x: a.BR.x, y: a.BR.y }; // BR (rotate)
      default: return { x: 0, y: 0 };
    }
  }

  /**
   * Handles clicks on image toolbar handles (resize/delete/duplicate/rotate).
   */
  function handleMouseDown(index: number, event: MouseEvent) {
    event.preventDefault();
    if (index === 1) { // Only for resize handle
      const rect = canvas.value!.getBoundingClientRect();
      const x = event.clientX - rect.left;
      const y = event.clientY - rect.top;
      for (let i = images.length - 1; i >= 0; i--) {
        const item = images[i];
        if (!item.isSelected) continue;
        const size = handleStyles.size * 2;
        const a = getAABBCorners(item);
        const handles = [
          [a.TL.x, a.TL.y],
          [a.TR.x, a.TR.y],
          [a.BL.x, a.BL.y],
          [a.BR.x, a.BR.y],
        ];
        const hx = handles[1][0];
        const hy = handles[1][1];
        if (
          x >= hx - size / 2 && x <= hx + size / 2 &&
          y >= hy - size / 2 && y <= hy + size / 2
        ) {
          dragState.image.resizeHandle = 1;
          dragState.image.resizingIndex = i;
          mouseDown.value = true;
          return;
        }
      }
    }
  }

  /**
   * Executes image-level actions triggered through the floating toolbar.
   */
  function handleImageClick(index: number) {
    const img = selectedObject.value as ImageObject;
    if (!img || img.type !== 'image') return;

    switch (index) {
      case 0: // delete
        images.splice(images.indexOf(img), 1);
        selectedObject.value = null;
        break;
      case 2: // duplicate
        const imgClone = { ...img, id: crypto.randomUUID?.() || Date.now().toString() };
        imgClone.x += 20;
        imgClone.y += 20;
        images.push(imgClone);
        break;
      case 3: // rotate
        img.rotation = ((img.rotation || 0) + 90) % 360;
        clampIntoGrid(img);
        break;
    }
    draw();
  }

  const handleStyles = {
    size: 14,
    color: '#0af',
    borderRadius: 0, // for future use if needed
    lineHeight: '1rem'
  };


  // Guide area constants
  const selectedView = ref<View>('Front');

  const DEFAULT_GRID: DesignGrid = {
    x: 175,
    y: 75,
    w: 250,
    h: 450,
    widthInches: undefined,
    heightInches: undefined,
    dpi: null,
    auto: null,
    autoGenerated: null,
  };

  // -----------------------------------------------------
  // Grid Configuration & Measurement Helpers
  // -----------------------------------------------------

  const {
    showGrid,
    clothingDetails,
    lastDetectionMetrics,
    resolveGrid,
    markGridManual,
    shouldAutoDetect,
    requestMeasurementRefresh,
    getPixelsPerInch,
    resetClothingDetails,
  } = createGridState(DEFAULT_GRID);

  // -----------------------------------------------------
  // View Management
  // -----------------------------------------------------

  /**
   * Persists current view state, switches to the requested view, and refreshes the canvas.
   */
  function switchView(next: View, options: { skipStore?: boolean } = {}) {
    const { skipStore = false } = options;
    // Allow switching even if already on the side, always store state and update preview
    const previous = selectedView.value;
    if (!skipStore) {
      storeViewState(previous);
      updatePreviewFor(previous, { skipBackground: !shirtBgLoaded.value });
    }

    selectedView.value = next;
    setShirtBackground(viewToSrc[next] || viewToSrc.Front || '', { mirror: viewMirrored[next] });
    loadViewState(next);
    requestAutoGrid(false);
  }

  /**
   * Maps UI labels to internal view keys and forwards to `switchView`.
   */
  function handleViewSelect(label: string) {
    let view: View = 'Front';
    if (label === 'Back') view = 'Back';
    switchView(view);
  }

  /**
   * Horizontally centers the active text block within the current grid bounds.
   */
  function centerSelectedText() {
    const t = selectedObject.value;
    if (!t || t.type !== 'text') return;

    const ctx = canvas.value?.getContext('2d');
    if (!ctx) return;

    const block = layoutTextBlock(ctx, t);
    const grid = clothingDetails.value.grid;

    t.x = grid.x + (grid.w - block.width) / 2;

    draw();
  }

  /**
   * Clones the active text block with a slight offset for quick iteration.
   */
  function duplicateSelectedText() {
    const t = selectedObject.value as any;
    if (!t || t.type !== 'text') return;
    const clone = {
      ...t,
      id: (typeof crypto !== 'undefined' && 'randomUUID' in crypto)
        ? crypto.randomUUID()
        : `t-${Date.now()}`,
      x: t.x + 10,
      y: t.y + 10,
      isSelected: true,
    };
    // deselect originals, select clone
    texts.forEach((x: any) => (x.isSelected = false));
    texts.push(clone);
    selectedObject.value = clone;
    draw();
  }

  /**
   * Raises the active object to the top of the z-stack.
   */
  function bringSelectedForward() {
    const sel = selectedObject.value as any;
    if (!sel) return;
    const { maxZ } = getZExtrema();
    sel.z = (maxZ || 0) + 1;
    rebalanceZ();
    draw();
  }

  /**
   * Sends the active object to the back of the z-stack.
   */
  function sendSelectedBack() {
    const sel = selectedObject.value as any;
    if (!sel) return;
    const { minZ } = getZExtrema();
    sel.z = (isFinite(minZ) ? minZ : 1) - 1;
    rebalanceZ();
    draw();
  }
  // Listen for clothing selection events from parent
  // If using v-on="selectClothing" directly, receive as prop instead, or use event bus.
  // Here, we'll assume you receive it as a prop or via a custom event.
  /**
   * Reacts to external "selectClothing" events from the surrounding application.
   */
  function handleClothingSelect(details: any) {
    if (!details) return;
    updateClothing(details);

    resetDesignState('Front');
    setShirtBackground(viewToSrc.Front || '', { mirror: viewMirrored.Front });
    draw();
  }

  const clothingSelectionHandler: EventListener = (event: Event) => {
    const custom = event as CustomEvent;
    handleClothingSelect(custom.detail);
  };

  const fileInput = ref<HTMLInputElement | null>(null);

  // -----------------------------------------------------
  // Canvas Setup & Background Assets
  // -----------------------------------------------------

  const mouseDown = ref(false);

  const canvas = ref<HTMLCanvasElement | null>(null);
  const canvasWidth = 600;
  const canvasHeight = 600;
  const BACKGROUND_VERTICAL_OFFSET = -150;

  const pendingAutoGrid = ref(false);
  let autoGridFrame: number | null = null;

  /**
   * Schedules automatic grid detection once the background image is available.
   */
  function requestAutoGrid(immediate = false) {
    if (!shouldAutoDetect()) return;
    pendingAutoGrid.value = true;
    if (immediate && shirtBgLoaded.value) {
      scheduleAutoGridMeasurement();
    }
  }

  /**
   * Executes auto grid measurement on the next animation frame, if pending.
   */
  function scheduleAutoGridMeasurement() {
    if (!pendingAutoGrid.value || !shirtBgLoaded.value) return;
    if (autoGridFrame !== null) return;
    autoGridFrame = requestAnimationFrame(() => {
      autoGridFrame = null;
      if (!pendingAutoGrid.value) return;
      autoFitGridFromBackground();
      pendingAutoGrid.value = false;
    });
  }

  function cancelAutoGridMeasurement() {
    if (autoGridFrame !== null) {
      cancelAnimationFrame(autoGridFrame);
      autoGridFrame = null;
    }
  }

  const canvasCursor = ref("default");
  const shirtBgLoaded = ref(false);
  const shirtBgError = ref<string | null>(null);
  const shirtBgMirrored = ref(false);
  const shirtBg = new window.Image();
  shirtBg.crossOrigin = 'anonymous';

  /**
   * Loads the garment image, wiring success/error handling and auto-detect refresh.
   */
  function setShirtBackground(src?: string | null, options: { mirror?: boolean } = {}) {
    const next = src || '';
    shirtBgLoaded.value = false;
    shirtBgError.value = null;
    shirtBgMirrored.value = Boolean(options.mirror);

    if (!next) {
      shirtBg.src = '';
      draw();
      cancelAutoGridMeasurement();
      pendingAutoGrid.value = false;
      return;
    }

    shirtBg.onload = () => {
      shirtBgLoaded.value = true;
      shirtBgError.value = null;
      draw();
      scheduleAutoGridMeasurement();
    };
    shirtBg.onerror = () => {
      shirtBgLoaded.value = false;
      shirtBgError.value = `Failed to load shirt image: ${next}`;
      draw();
      cancelAutoGridMeasurement();
      pendingAutoGrid.value = false;
    };
    shirtBg.src = next;
  }

  // ---- Garment background transform (for fine alignment) ----
  const bgTransform = reactive({ offsetX: 0, offsetY: 150, scale: 1 });
  /**
   * Applies manual background adjustments and requests a fresh auto grid.
   */
  function setBackgroundTransform(t: { offsetX?: number; offsetY?: number; scale?: number }) {
    if (typeof t.offsetX === 'number') bgTransform.offsetX = t.offsetX;
    if (typeof t.offsetY === 'number') bgTransform.offsetY = t.offsetY;
    if (typeof t.scale === 'number') bgTransform.scale = t.scale;
    draw();
    requestAutoGrid(true);
  }

  // -----------------------------------------------------
  const ALL_VIEWS: View[] = ['Front', 'Back'];

  // View Asset Mapping & Previews
  // -----------------------------------------------------

  const viewToSrc = reactive<Record<View, string>>({
    Front: props.clothing?.front || props.clothing?.colors?.[0]?.background || '',
    Back: props.clothing?.back || props.clothing?.front || props.clothing?.colors?.[0]?.background || '',
  });
  const viewMirrored = reactive<Record<View, boolean>>({
    Front: false,
    Back: false,
  });
  const viewStates: Record<View, { images: ImageObject[]; texts: TextObject[] }> = {
    Front: { images: [], texts: [] },
    Back: { images: [], texts: [] },
  };

  const frontPreview = ref<string>('');
  const backPreview = ref<string>('');

  function refreshAllPreviews() {
    for (const view of ALL_VIEWS) {
      const src = viewToSrc[view] || fallbackPreview;
      setPreview(view, src);
    }
  }

  function setPreview(view: View, url: string) {
    if (view === 'Front') {
      frontPreview.value = url;
    } else if (view === 'Back') {
      backPreview.value = url;
    }
  }

  function cloneImageObject(item: ImageObject): ImageObject {
    return {
      ...item,
      // do not store live element
      imgUrl: item.imgUrl // keep only the source
    };
  }

  function cloneTextObject(item: TextObject): TextObject {
    return {
      ...item,
      effect: {
        ...item.effect,
        options: { ...item.effect.options },
      },
    };
  }

  /**
   * Clears previews, selections, and per-view caches before loading a new garment/view.
   */
  function resetDesignState(target: View = 'Front') {
    images.splice(0, images.length);
    texts.splice(0, texts.length);
    viewStates.Front = { images: [], texts: [] };
    viewStates.Back = { images: [], texts: [] };
    frontPreview.value = '';
    backPreview.value = '';
    selectedObject.value = null;
    storeViewState('Front');
    selectedView.value = target;
    loadViewState(target);
  }

  function storeViewState(view: View) {
    const state = viewStates[view];
    state.images = images.map(cloneImageObject);
    state.texts = texts.map(cloneTextObject);
  }

  function loadViewState(view: View) {
    const state = viewStates[view] ?? { images: [], texts: [] };
    images.splice(0, images.length, ...state.images.map(cloneImageObject));
    texts.splice(0, texts.length, ...state.texts.map(cloneTextObject));
    selectedObject.value = null;
    images.forEach((img) => (img.isSelected = false));
    texts.forEach((txt) => (txt.isSelected = false));
    const { maxZ } = getZExtrema();
    zCounter.value = (isFinite(maxZ) ? maxZ : 0) + 1;

    // Rehydrate <img> for each image (CORS-safe)
    for (const img of images) {
      if (img && img.imgUrl) {
        const imageEl = new Image();
        imageEl.crossOrigin = 'anonymous';
        imageEl.src = img.imgUrl as any;
        imageEl.onload = () => {
          (img as any).img = imageEl;
          draw(); // redraw as each image loads
        };
      }
    }

    draw();
  }

  function updatePreviewFor(view: View, { skipBackground = false } = {}) {
    if (skipBackground) return;
    // Build a full-canvas preview (background + objects only; no grid or rulers)
    const buildFull = (ctx: CanvasRenderingContext2D, includeBackground: boolean) => {
      // 1) Background (shirt), optional to avoid CORS taint
      if (includeBackground && !skipBackground) {
        try {
          drawShirtBg(ctx);
        } catch (e) {
          console.warn('[updatePreviewFor] drawShirtBg failed in preview:', e);
        }
      } else {
        // fill with white so previews look clean without bg
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, canvasWidth, canvasHeight);
      }

      // 2) (Omit grid lines and rulers for preview images)
      // (Grid and rulers intentionally omitted in preview.)

      // 3) Objects (images + text) in z-order
      const ordered = getAllObjectsByZ() as Array<any>;
      for (const obj of ordered) {
        if (obj.type === 'image') {
          const item = obj as any;
          if (!item.img || !(item.img instanceof Image)) continue; // skip until loaded

          ctx.save();
          const cx = item.x + item.w / 2;
          const cy = item.y + item.h / 2;
          ctx.translate(cx, cy);
          ctx.rotate(((item.rotation || 0) * Math.PI) / 180);
          ctx.drawImage(item.img, -item.w / 2, -item.h / 2, item.w, item.h);
          ctx.restore();
        } else if (obj.type === 'text') {
          const t = obj as any;
          const block = layoutTextBlock(ctx, t);
          const eff = t.effect && t.effect.name ? t.effect : { name: 'none', options: withDefaults('none') };
          const effName = eff.name;
          const effOpts = withDefaults(eff.name, eff.options);

          ctx.font = `${block.pxSize}px ${t.font}`;
          ctx.fillStyle = t.color;
          ctx.strokeStyle = t.outlineColor;
          ctx.lineWidth = t.outlineWidth;
          ctx.textBaseline = 'alphabetic';
          ctx.textAlign = t.alignment;

          let y = t.y;
          for (let li = 0; li < block.lines.length; li++) {
            const ln = block.lines[li];
            const anchor = block.lineX[li];
            const chars = Array.from(ln);
            if (!chars.length) { y += block.lineHeight; continue; }

            const advances = chars.map(ch => ctx.measureText(ch).width);
            let cursorX = (() => {
              if (t.alignment === 'center') return anchor - (advances.reduce((a, b) => a + b, 0)) / 2;
              if (t.alignment === 'right') return anchor - (advances.reduce((a, b) => a + b, 0));
              return anchor;
            })();

            for (let i = 0; i < chars.length; i++) {
              const ch = chars[i];
              const tr = getEffectTransform(effName, i, chars.length, effOpts);
              ctx.save();
              applyToContext(ctx, cursorX, y, tr, 0, 0);
              ctx.fillText(ch, 0, 0);
              if (t.outlineColor && t.outlineColor !== 'None' && t.outlineWidth > 0) {
                ctx.strokeText(ch, 0, 0);
              }
              ctx.restore();
              cursorX += advances[i];
            }

            y += block.lineHeight;
          }
        }
      }
    };

    // Helper: Crop a canvas to the non-transparent content
    function cropCanvasToContent(sourceCanvas: HTMLCanvasElement): HTMLCanvasElement {
      const ctx = sourceCanvas.getContext('2d');
      if (!ctx) return sourceCanvas;
      const { width, height } = sourceCanvas;
      const imageData = ctx.getImageData(0, 0, width, height);
      const data = imageData.data;
      let minX = width, minY = height, maxX = -1, maxY = -1;
      for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
          const idx = (y * width + x) * 4;
          if (data[idx + 3] > 0) { // alpha > 0 means not transparent
            if (x < minX) minX = x;
            if (x > maxX) maxX = x;
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
          }
        }
      }
      // If no non-transparent pixel found, return a 1x1 transparent canvas
      if (maxX < minX || maxY < minY) {
        const empty = document.createElement('canvas');
        empty.width = 1;
        empty.height = 1;
        return empty;
      }
      const cropW = maxX - minX + 1;
      const cropH = maxY - minY + 1;
      const croppedCanvas = document.createElement('canvas');
      croppedCanvas.width = cropW;
      croppedCanvas.height = cropH;
      const croppedCtx = croppedCanvas.getContext('2d');
      if (!croppedCtx) return sourceCanvas;
      croppedCtx.drawImage(sourceCanvas, minX, minY, cropW, cropH, 0, 0, cropW, cropH);
      return croppedCanvas;
    }

    try {
      // Always build an offscreen preview (never clone live canvas directly)
      const previewCanvas = document.createElement('canvas');
      previewCanvas.width = canvasWidth;
      previewCanvas.height = canvasHeight;
      const ctx = previewCanvas.getContext('2d');
      if (!ctx) return;

      // Attempt with background included
      buildFull(ctx, true);
      try {
        const cropped = cropCanvasToContent(previewCanvas);
        const url = cropped.toDataURL('image/png');
        setPreview(view, url);
        return;
      } catch (bgErr) {
        console.warn('[updatePreviewFor] toDataURL failed with background (likely CORS). Falling back to no background.', bgErr);
      }

      // Fallback: rebuild without background to avoid taint
      ctx.clearRect(0, 0, canvasWidth, canvasHeight);
      buildFull(ctx, false);
      const cropped = cropCanvasToContent(previewCanvas);
      const url = cropped.toDataURL('image/png');
      setPreview(view, url);
    } catch (err) {
      console.warn('[updatePreviewFor] failed to build full-canvas preview:', err);
    }
  }

  /**
   * Reads image uploads and routes them through the unified object pipeline.
   */
  function onFileChange(e: Event) {
    const files = (e.target as HTMLInputElement).files;
    if (!files) return;
    for (const file of files) {
      const reader = new FileReader();
      reader.onload = function (ev) {
        // Use uploadObject for image
        const result = ev.target?.result;
        if (typeof result === 'string') {
          uploadObject('image', { imgUrl: result });
        }
      };
      reader.readAsDataURL(file);
    }
  }

  /**
   * Returns the scaled placement of the garment image within the canvas viewport.
   */
  function computeShirtTransform(imageWidth: number, imageHeight: number) {
    const iw = Math.max(1, imageWidth);
    const ih = Math.max(1, imageHeight);
    const baseScale = Math.min(canvasWidth / iw, canvasHeight / ih);
    const scale = baseScale * (bgTransform.scale || 1);
    const width = iw * scale;
    const height = ih * scale;
    const offsetX = (canvasWidth - width) / 2 + (bgTransform.offsetX || 0);
    const offsetY = (canvasHeight - height) / 2 + (bgTransform.offsetY || 0) + BACKGROUND_VERTICAL_OFFSET;
    return { scale, width, height, offsetX, offsetY };
  }

  /**
   * Renders the current garment image or a fallback when unavailable.
   */
  function drawShirtBg(ctx: CanvasRenderingContext2D) {
    if (shirtBgLoaded.value) {
      const iw = (shirtBg as any).naturalWidth || shirtBg.width || 1;
      const ih = (shirtBg as any).naturalHeight || shirtBg.height || 1;
      const { width, height, offsetX, offsetY } = computeShirtTransform(iw, ih);
      if (shirtBgMirrored.value) {
        ctx.save();
        ctx.translate(offsetX + width, offsetY);
        ctx.scale(-1, 1);
        ctx.drawImage(shirtBg, 0, 0, width, height);
        ctx.restore();
      } else {
        ctx.drawImage(shirtBg, offsetX, offsetY, width, height);
      }
    } else if (shirtBgError.value) {
      ctx.fillStyle = '#9ca3af';
      ctx.font = '16px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Image unavailable', canvasWidth / 2, canvasHeight / 2);
    }
  }

  // --- Text wrapping + measurement helper ---
  // --- Text wrapping + measurement helper (now wraps long words) ---
  // --- Text wrapping + measurement helper (no double-push, breaks long words) ---
  // Glyph-tight layout that accounts for overshoots (H, J, swashes, etc.)
  // Glyph-tight layout + word wrap + alignment
  // Word-only wrap (no letter-by-letter splits, no hyphens)
  /**
   * Performs glyph-aware word wrapping and metrics gathering for a text object.
   */
  function layoutTextBlock(ctx: CanvasRenderingContext2D, t: TextObject) {
    const basePx = Math.max(1, getPixelsPerInch());
    const pxSize = t.size * basePx;
    ctx.font = `${pxSize}px ${t.font}`;
    ctx.textBaseline = 'alphabetic';
    ctx.textAlign = t.alignment;

    // metrics
    const probe = ctx.measureText('Mg');
    const ascent = probe.actualBoundingBoxAscent || pxSize * 0.75;
    const descent = probe.actualBoundingBoxDescent || pxSize * 0.25;
    const lineHeight = (ascent + descent) * 1.2;

    // fixed textbox width, capped by grid (keeps box stable)
    const grid = clothingDetails.value.grid;
    const rawW = Number.isFinite(t.w as any) ? Number(t.w) : grid.w;
    const boxWidth = Math.max(20, Math.min(rawW, grid.w));
    const maxWidth = boxWidth;

    // wrap one paragraph by words only
    function wrapParagraph(text: string): string[] {
      const words = text.split(/\s+/).filter(Boolean);
      if (!words.length) return [''];

      const out: string[] = [];
      let line = '';

      for (const w of words) {
        const test = line ? line + ' ' + w : w;
        if (ctx.measureText(test).width <= maxWidth) {
          line = test;
        } else {
          if (line) out.push(line);
          // word alone too wide? keep it whole on its own line (no mid-word break)
          line = w;
        }
      }
      if (line) out.push(line);
      return out;
    }

    // support explicit newlines
    const paragraphs = String(t.content ?? '').split(/\r?\n/);
    const lines: string[] = [];
    for (let p = 0; p < paragraphs.length; p++) {
      const wrapped = wrapParagraph(paragraphs[p]);
      lines.push(...wrapped);
      // (optional) preserve blank line between paragraphs: lines.push('');
    }
    if (!lines.length) lines.push('');

    // per-line widths + aligned start X (text sits inside the fixed box)
    const lineWidths = lines.map(ln => ctx.measureText(ln).width);
    // anchor X used for drawing (respect alignment) but keep within the fixed box [t.x .. t.x + maxWidth]
    const anchorX = (
      t.alignment === 'center' ? t.x + maxWidth / 2 :
        t.alignment === 'right' ? t.x + maxWidth :
          t.x
    );
    const lineX = lineWidths.map(() => anchorX);

    // alignment-aware bounds over all lines based on visual placement
    let minLeft = Infinity, maxRight = -Infinity;

    for (let li = 0; li < lines.length; li++) {
      const w = lineWidths[li];
      const anchor = lineX[li];
      const left = (t.alignment === 'center') ? anchor - w / 2
        : (t.alignment === 'right') ? anchor - w
          : anchor; // left
      const right = left + w;
      if (left < minLeft) minLeft = left;
      if (right > maxRight) maxRight = right;
    }

    // vertical extent from first baseline to last, plus ascent/descent
    const minTop = t.y - ascent;
    const maxBottom = t.y + (lines.length - 1) * lineHeight + descent;

    // fallback for empty content
    if (!isFinite(minLeft)) {
      minLeft = t.x;
      maxRight = t.x;
    }

    const pad = (t.outlineWidth || 0) * 0.5 + 1;
    const boundsLeft = minLeft - pad;
    const boundsTop = minTop - pad;
    const boundsRight = maxRight + pad;
    const boundsBottom = maxBottom + pad;

    return {
      lines,
      lineWidths,
      lineX,
      pxSize,
      lineHeight,
      ascent,
      descent,
      boundsLeft,
      boundsTop,
      boundsRight,
      boundsBottom,
      width: boundsRight - boundsLeft,
      height: boundsBottom - boundsTop,
    };
  }

  function isMultiple(value: number, unit: number, epsilon = 0.1) {
    if (!unit || !Number.isFinite(unit)) return false;
    const scaled = value / unit;
    return Math.abs(scaled - Math.round(scaled)) <= epsilon;
  }

  // Draw rulers (call after grid lines, before objects)
  /**
   * Draws inch-based rulers around the active grid using the current DPI estimate.
   */
  function drawRulers(ctx: CanvasRenderingContext2D, gridX: number, gridY: number, gridWidth: number, gridHeight: number) {
    const inchPx = getPixelsPerInch();
    if (!Number.isFinite(inchPx) || inchPx <= 0) return;

    const quarterStep = inchPx / 4;
    if (!Number.isFinite(quarterStep) || quarterStep <= 0.5) return;

    ctx.save();
    ctx.strokeStyle = '#000000';
    ctx.fillStyle = '#000000';
    ctx.font = '10px "Anek Latin", sans-serif';
    ctx.textBaseline = 'top';
    ctx.lineWidth = 1;

    const maxX = gridWidth + quarterStep / 2;
    const maxY = gridHeight + quarterStep / 2;

    // Top ruler
    ctx.textAlign = 'center';
    for (let offset = 0; offset <= maxX; offset += quarterStep) {
      const px = gridX + offset;
      const isInch = isMultiple(offset, inchPx);
      const isHalf = !isInch && isMultiple(offset, inchPx / 2);
      const tickHeight = isInch ? 10 : (isHalf ? 7 : 4);
      ctx.beginPath();
      ctx.moveTo(px, gridY);
      ctx.lineTo(px, gridY - tickHeight);
      ctx.stroke();
      if (isInch && offset > 0) {
        const inches = offset / inchPx;
        const label = inches.toFixed(1).replace(/\.0$/, '');
        ctx.fillText(label, px, gridY - 25);
      }
    }

    // Left ruler
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    for (let offset = 0; offset <= maxY; offset += quarterStep) {
      const py = gridY + offset;
      const isInch = isMultiple(offset, inchPx);
      const isHalf = !isInch && isMultiple(offset, inchPx / 2);
      const tickWidth = isInch ? 10 : (isHalf ? 7 : 4);
      ctx.beginPath();
      ctx.moveTo(gridX, py);
      ctx.lineTo(gridX - tickWidth, py);
      ctx.stroke();
      if (isInch && offset > 0) {
        const inches = offset / inchPx;
        const label = inches.toFixed(1).replace(/\.0$/, '');
        ctx.fillText(label, gridX - 15, py);
      }
    }

    ctx.restore();
  }

  /**
   * Main canvas renderer combining background, guides, and ordered objects.
   */
  function draw() {
    const ctx = canvas.value?.getContext('2d');
    if (!ctx) return;
    ctx.clearRect(0, 0, canvasWidth, canvasHeight);
    drawShirtBg(ctx);

    if (showGrid.value) {
      const gridRect = resolveGrid();
      // Draw grid
      ctx.save();
      ctx.strokeStyle = "#bbb";
      ctx.lineWidth = 1;
      const inchPx = getPixelsPerInch();
      const candidateStep = inchPx / 2;
      const gridStep = (Number.isFinite(candidateStep) && candidateStep > 4) ? candidateStep : 40;
      for (let x = gridRect.x; x <= gridRect.x + gridRect.w; x += gridStep) {
        ctx.beginPath();
        ctx.moveTo(x, gridRect.y);
        ctx.lineTo(x, gridRect.y + gridRect.h);
        ctx.stroke();
      }
      for (let y = gridRect.y; y <= gridRect.y + gridRect.h; y += gridStep) {
        ctx.beginPath();
        ctx.moveTo(gridRect.x, y);
        ctx.lineTo(gridRect.x + gridRect.w, y);
        ctx.stroke();
      }
      // Draw guide border
      ctx.strokeStyle = "#4af";
      ctx.lineWidth = 2;
      ctx.strokeRect(gridRect.x, gridRect.y, gridRect.w, gridRect.h);

      // Draw boundary resize handles if creating


      ctx.restore();

      // --- Draw rulers after grid, before objects ---
      drawRulers(
        ctx,
        gridRect.x,
        gridRect.y,
        gridRect.w,
        gridRect.h
      );
    }

    // --- Unified z-ordered rendering of images and text ---
    const ordered = getAllObjectsByZ() as Array<any>;
    for (const obj of ordered) {
      if (obj.type === 'image') {
        const item = obj as any;
        // Skip until the img element exists
        if (!item.img || !(item.img instanceof Image)) continue;

        ctx.globalAlpha = 1;
        ctx.save();
        const cx = item.x + item.w / 2;
        const cy = item.y + item.h / 2;
        ctx.translate(cx, cy);
        ctx.rotate(((item.rotation || 0) * Math.PI) / 180);
        // draw the image centered in its frame; frame size stays constant
        ctx.drawImage(item.img, -item.w / 2, -item.h / 2, item.w, item.h);
        ctx.restore();

        if (item.isSelected) {
          const { TL, TR, BR, BL } = getRotatedCorners(item);
          ctx.save();
          ctx.strokeStyle = '#0af';
          ctx.lineWidth = 2;
          ctx.fillStyle = 'rgba(0, 200, 255, 0.15)';
          ctx.beginPath();
          ctx.moveTo(TL.x, TL.y);
          ctx.lineTo(TR.x, TR.y);
          ctx.lineTo(BR.x, BR.y);
          ctx.lineTo(BL.x, BL.y);
          ctx.closePath();
          ctx.stroke();
          ctx.fill();
          ctx.restore();
        }
      } else if (obj.type === 'text') {
        const t = obj as any;
        // layout
        const block = layoutTextBlock(ctx, t);


        // styles
        const eff = t.effect && t.effect.name ? t.effect : { name: 'none', options: withDefaults('none') };
        const effName = eff.name;
        const effOpts = withDefaults(eff.name, eff.options); // ensure all knobs present


        ctx.font = `${block.pxSize}px ${t.font}`;
        ctx.fillStyle = t.color;
        ctx.strokeStyle = t.outlineColor;
        ctx.lineWidth = t.outlineWidth;
        ctx.textBaseline = 'alphabetic';
        ctx.textAlign = t.alignment;

        let y = t.y;

        for (let li = 0; li < block.lines.length; li++) {
          const ln = block.lines[li];
          const anchor = block.lineX[li]; // your existing anchor (left/center/right)

          const chars = Array.from(ln);
          if (!chars.length) { y += block.lineHeight; continue; }

          // measure base advances once
          const advances = chars.map(ch => ctx.measureText(ch).width);
          const baseWidth = advances.reduce((a, b) => a + b, 0);

          // compute per-glyph extra spacing from the effect
          const extras = chars.map(() => getEffectAdvance(effName));
          const extraSum = extras.reduce((a, b) => a + b, 0);
          const effWidth = baseWidth + extraSum;

          // convert your anchor to a leftX that preserves position
          // - left: anchor is left edge
          // - center: keep center fixed -> shift left by effWidth/2
          // - right: keep right edge fixed -> shift left by effWidth
          let leftX = anchor;
          if (t.alignment === 'center') leftX = anchor - effWidth / 2;
          else if (t.alignment === 'right') leftX = anchor - effWidth;

          // per-glyph draw at fixed baseline y, starting from leftX
          let cursorX = leftX;
          for (let i = 0; i < chars.length; i++) {
            // inside the glyph loop
            const ch = chars[i];
            const tr = getEffectTransform(effName, i, chars.length, effOpts);

            // pivot: top of the glyph for 'spreadOut'; baseline for others
            let originY = 0;
            if (effName === 'spreadOut') {
              const m = ctx.measureText(ch);
              const ascent = m.actualBoundingBoxAscent ?? block.pxSize * 0.8; // fallback if metric missing
              originY = -ascent; // pivot at top so scaleY grows downward
            }

            ctx.save();
            applyToContext(ctx, cursorX, y, tr, 0, originY); // originX=0 is fine
            ctx.fillText(ch, 0, 0);
            if (t.outlineColor && t.outlineColor !== 'None' && t.outlineWidth > 0) {
              ctx.strokeText(ch, 0, 0);
            }
            ctx.restore();

            cursorX += advances[i] /* + extras[i] if you had any */;
          }

          y += block.lineHeight;
        }


        if (t.isSelected) {
          ctx.save();
          ctx.strokeStyle = '#0af';
          ctx.lineWidth = 1.5;
          ctx.fillStyle = 'rgba(0, 200, 255, 0.15)';
          ctx.strokeRect(block.boundsLeft, block.boundsTop, block.width, block.height);
          ctx.fillRect(block.boundsLeft, block.boundsTop, block.width, block.height);
          // Do not set selectedObject.value here!
          ctx.restore();
        }
      }
    }

    updatePreviewFor(selectedView.value, { skipBackground: !shirtBgLoaded.value });
  }



  onMounted(draw);

  /**
   * Hit-tests all drawable objects in z-order to find the top-most match.
   */
  function findObjectAt(x: number, y: number): { type: 'image' | 'text'; index: number } | null {
    const ctx = canvas.value?.getContext('2d');
    const ordered = getAllObjectsByZ() as Array<any>;
    // Walk from topmost to backmost
    for (let i = ordered.length - 1; i >= 0; i--) {
      const obj = ordered[i];
      if (obj.type === 'text') {
        if (!ctx) continue;
        const block = layoutTextBlock(ctx, obj);
        const bx = block.boundsLeft;
        const by = block.boundsTop;
        if (x >= bx && x <= bx + block.width && y >= by && y <= by + block.height) {
          const tIndex = texts.findIndex(t => t.id === obj.id);
          if (tIndex !== -1) return { type: 'text', index: tIndex };
        }
      } else if (obj.type === 'image') {
        if (pointInRotatedRect(x, y, obj)) {
          const iIndex = images.findIndex(im => im.id === obj.id);
          if (iIndex !== -1) return { type: 'image', index: iIndex };
        }
      }
    }
    return null;
  }


  /**
   * Updates the canvas cursor based on hovered handles or objects.
   */
  function onHover(e: MouseEvent) {
    const rect = canvas.value!.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;


    // --- Only show handle cursors for the SELECTED object ---
    const sel = selectedObject.value;

    if (sel && sel.type === 'image' && (sel as any).showHandles) {
      const item = sel as ImageObject;
      const size = handleStyles.size; // smaller hit area, matches startDrag
      const a = getAABBCorners(item);
      const handles: [number, number][] = [
        [a.TL.x, a.TL.y],
        [a.TR.x, a.TR.y],
        [a.BL.x, a.BL.y],
        [a.BR.x, a.BR.y],
      ];
      for (let h = 0; h < handles.length; h++) {
        const [hx, hy] = handles[h];
        if (x >= hx - size / 2 && x <= hx + size / 2 &&
          y >= hy - size / 2 && y <= hy + size / 2) {
          // Only TR should show resize cursor
          if (h === 1) canvasCursor.value = 'nesw-resize';
          else canvasCursor.value = 'pointer';
          return;
        }
      }
    }

    if (sel && sel.type === 'text' && (sel as any).showHandles) {
      // bottom-right handle for text (resize), matching your render positions
      const br = getTextHandlePosition('bottomRight');
      const size = handleStyles.size;
      if (x >= br.left - size / 2 && x <= br.left + size / 2 &&
        y >= br.top - size / 2 && y <= br.top + size / 2) {
        canvasCursor.value = 'ew-resize';
        return;
      }
    }

    // Check if over any image or text
    const found = findObjectAt(x, y);
    hoveredObject.value = found;
    if (found) {
      canvasCursor.value = 'move';
      return;
    }

    // Default
    canvasCursor.value = 'default';
  }

  const hoveredObject = ref<{ type: 'image' | 'text'; index: number } | null>(null);

  function onMove(e: MouseEvent) {
    if (mouseDown.value) {
      onDrag(e);
    } else {
      onHover(e);
    }
  }

  // Drag logic
  /**
   * Begins dragging for images or text depending on the hit-test result.
   */
  function startDrag(e: MouseEvent) {
    e.preventDefault();
    mouseDown.value = true;
    const rect = canvas.value!.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    // Check for guide boundary handles if in create mode


    // Try handles FIRST, starting with topmost images
    for (let i = images.length - 1; i >= 0; i--) {
      const item = images[i];
      if (!item.isSelected) continue;            // <-- key line

      const size = handleStyles.size;            // smaller hit area
      const handles = [
        [item.x, item.y],                         // TL
        [item.x + item.w, item.y],                // TR
        [item.x, item.y + item.h],                // BL
        [item.x + item.w, item.y + item.h],       // BR
      ];
      for (let h = 0; h < handles.length; h++) {
        const [hx, hy] = handles[h];
        if (
          x >= hx - size / 2 && x <= hx + size / 2 &&
          y >= hy - size / 2 && y <= hy + size / 2
        ) {
          images.forEach((img, idx) => (img.isSelected = idx === i));
          draw();
          switch (h) {
            case 0: // TL - delete
              // Do nothing here. Triggered on click only.
              return;
            case 1: // TR - resize
              dragState.image.resizeHandle = 1;
              dragState.image.resizingIndex = i;
              dragState.image.index = -1;
              return;
            case 2: // BL - duplicate
            case 3: // BR - rotate
              // Do nothing here. Triggered on click only.
              return;
          }
        }
      }
    }

    // --- Updated selection logic ---
    // Hit-test any object (z-ordered; topmost first)
    const found = findObjectAt(x, y);
    // Select images
    const imgIdx = found?.type === 'image' ? found.index : -1;
    images.forEach((img) => {
      img.isSelected = false;
    });
    texts.forEach(t => t.isSelected = false);

    if (found) {
      if (found.type === 'image') {
        const img = images[found.index];
        img.isSelected = true;
        selectedObject.value = img;
      } else if (found.type === 'text') {
        const t = texts[found.index];
        t.isSelected = true;
        selectedObject.value = t;

        // Enable dragging for text
        dragState.text.index = found.index;
        dragState.text.offset.x = x - t.x;
        dragState.text.offset.y = y - t.y;
      }
    } else {
      selectedObject.value = null;
    }


    // Image clicked: start image drag
    dragState.image.index = imgIdx;

    if (imgIdx !== -1) {
      dragState.image.offset.x = x - images[imgIdx].x;
      dragState.image.offset.y = y - images[imgIdx].y;
    } else {
      dragState.image.offset.x = 0;
      dragState.image.offset.y = 0;
    }
    draw();
  }

  /**
   * Central drag loop handling text resizing, guide manipulation, and object movement.
   */
  function onDrag(e: MouseEvent) {
    // Hide handles while dragging text
    if (selectedObject.value?.type === 'text' && dragState.text.index !== -1) {
      // Temporarily hide handles while dragging
      selectedObject.value.showHandles = false;
    }

    // Text box resize (width-only; rewrap handles height)
    if (dragState.text.isResizing && selectedObject.value?.type === 'text') {
      const t = selectedObject.value as TextObject;
      const rect = canvas.value!.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;

      const grid = clothingDetails.value.grid;
      const minW = 20;

      // Helper clamp
      const clamp = (val: number, lo: number, hi: number) => Math.max(lo, Math.min(val, hi));

      if (t.alignment === 'left') {
        // Anchor left, drag from the right
        const left = t.x;
        const maxW = (grid.x + grid.w) - left; // keep right edge <= grid right
        let targetW = mouseX - left;
        targetW = clamp(targetW, minW, maxW);
        t.w = targetW;
        draw();
        return;
      }

      if (t.alignment === 'right') {
        // Anchor right, move left handle; keep left edge >= grid.x
        const right = t.x + (t.w || 0);
        const maxW = right - grid.x; // so left >= grid.x
        let targetW = right - mouseX; // drag leftwards to grow
        targetW = clamp(targetW, minW, maxW);
        t.w = targetW;
        t.x = right - t.w; // recompute left so right stays fixed
        draw();
        return;
      }

      // center alignment
      {
        // Anchor center; expand/contract both sides symmetrically
        const center = t.x + (t.w || 0) / 2;
        let half = Math.abs(mouseX - center);
        // Constrain so both sides stay within grid
        const maxHalfLeft = center - grid.x;
        const maxHalfRight = (grid.x + grid.w) - center;
        const maxHalf = Math.max(minW / 2, Math.min(maxHalfLeft, maxHalfRight));
        half = clamp(half, minW / 2, maxHalf);
        const targetW = half * 2;
        t.x = center - targetW / 2;
        t.w = targetW;
        draw();
        return;
      }
    }
    e.preventDefault();
    const rect = canvas.value!.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    // If dragging a text box, move it
    if (dragState.text.index !== -1) {
      const t = texts[dragState.text.index];
      // Move text based on drag offset
      t.x = x - dragState.text.offset.x;
      t.y = y - dragState.text.offset.y;

      // Measure text size
      const ctx2 = canvas.value?.getContext('2d');
      if (ctx2) {
        const block = layoutTextBlock(ctx2, t);
        const grid = clothingDetails.value.grid;

        const minX = grid.x - (block.boundsLeft - t.x); // how far left we can move baseline before left bound hits grid
        const maxX = grid.x + grid.w - (block.boundsRight - t.x);
        const minY = grid.y - (block.boundsTop - t.y);
        const maxY = grid.y + grid.h - (block.boundsBottom - t.y);

        t.x = Math.max(minX, Math.min(t.x, maxX));
        t.y = Math.max(minY, Math.min(t.y, maxY));
      }
      draw();
      return;
    }
    // Guide boundary resizing logic
    if (dragState.guide.handle !== -1) {
      const xPos = x;
      const yPos = y;

      markGridManual();
      switch (dragState.guide.handle) {

        case 0: // TR
          clothingDetails.value.grid.w = xPos - clothingDetails.value.grid.x;
          clothingDetails.value.grid.h += clothingDetails.value.grid.y - yPos;
          clothingDetails.value.grid.y = yPos;
          break;

        case 4: // Top
          clothingDetails.value.grid.h += clothingDetails.value.grid.y - yPos;
          clothingDetails.value.grid.y = yPos;
          break;
        case 5: // Bottom
          clothingDetails.value.grid.h = yPos - clothingDetails.value.grid.y;
          break;
        case 6: // Left
          clothingDetails.value.grid.w += clothingDetails.value.grid.x - xPos;
          clothingDetails.value.grid.x = xPos;
          break;
        case 7: // Right
          clothingDetails.value.grid.w = xPos - clothingDetails.value.grid.x;
          break;
      }

      // Minimum size
      clothingDetails.value.grid.w = Math.max(50, clothingDetails.value.grid.w);
      clothingDetails.value.grid.h = Math.max(50, clothingDetails.value.grid.h);

      draw();
      return;
    }

    // Drag guide boundary by center if in create mode
    if (dragState.guide.isDragging) {
      const xPos = x;
      const yPos = y;
      markGridManual();
      clothingDetails.value.grid.x = xPos - dragState.guide.offset.x;
      clothingDetails.value.grid.y = yPos - dragState.guide.offset.y;
      draw();
      return;
    }

    // Only allow resizing from TR handle (index 1)
    if (dragState.image.resizeHandle === 1 && dragState.image.resizingIndex !== -1) {
      const item = images[dragState.image.resizingIndex];
      // Keep frame aspect constant regardless of rotation
      const effAspect = item.aspect;
      // Anchor at bottom-left
      const [anchorX, anchorY] = [item.x, item.y + item.h];
      // Calculate new width and maintain aspect ratio
      let newW = x - anchorX;
      newW = Math.max(20, newW); // minimum width
      let newH = newW / effAspect;
      // Clamp to grid bounds
      const grid = clothingDetails.value.grid;
      const maxW = grid.x + grid.w - anchorX;
      const maxH = anchorY - grid.y;
      if (newW > maxW) {
        newW = maxW;
        newH = newW / effAspect;
      }
      if (newH > maxH) {
        newH = maxH;
        newW = newH * effAspect;
      }
      item.w = newW;
      item.h = newH;
      // Keep bottom-left anchor fixed
      item.y = anchorY - item.h;
      item.isSelected = true;
      // Ensure rotated AABB stays within grid after resize
      clampIntoGrid(item);
      draw();
      return;
    }
    if (dragState.image.index === -1) return;
    const item = images[dragState.image.index];
    item.x = x - dragState.image.offset.x;
    item.y = y - dragState.image.offset.y;

    // Constrain position using rotated AABB so it stays inside grid
    clampIntoGrid(item);

    draw();
  }

  /**
   * Ends any active drag, resets cursor state, and cleans up window listeners.
   */
  function stopDrag() {
    if (onWinMove) window.removeEventListener('mousemove', onWinMove);
    if (onWinUp) window.removeEventListener('mouseup', onWinUp);
    onWinMove = null;
    onWinUp = null;

    // Show handles again after drag stops (for text)
    if (selectedObject.value?.type === 'text') {
      (selectedObject.value as any).__minLock = false; // reset min-width lock
      selectedObject.value.showHandles = true;
    }
    mouseDown.value = false;
    dragState.image.index = -1;
    dragState.image.resizeHandle = -1;
    dragState.image.resizingIndex = -1;
    dragState.image.offset.x = 0;
    dragState.image.offset.y = 0;
    dragState.guide.handle = -1;
    dragState.guide.isDragging = false;
    dragState.guide.offset.x = 0;
    dragState.guide.offset.y = 0;
    dragState.text.isResizing = false;
    dragState.text.index = -1;
    dragState.text.offset.x = 0;
    dragState.text.offset.y = 0;
  }

  /**
   * Programmatically triggers the hidden file input to upload assets.
   */
  function openFileDialog() {
    fileInput.value?.click();
  }

  // Unified object upload (image/text) with correct type signatures
  /**
   * Creates text or image objects and inserts them into the shared layer stack.
   */
  function uploadObject(
    type: 'image',
    payload: { imgUrl: string }
  ): void;
  function uploadObject(
    type: 'text',
    payload: {
      content?: string;
      font?: string[];
      color?: string;
      outlineColor?: string;
      outlineWidth?: number;
      size?: number;
      alignment?: 'left' | 'center' | 'right';
      rotation?: number;
    }
  ): void;
  function uploadObject(type: 'image' | 'text', payload: any) {
    if (type === 'image') {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.src = payload.imgUrl;

      img.onload = () => {
        deselectAll()
        images.forEach(i => i.isSelected = false);

        const w = Math.min(img.width / 3, clothingDetails.value.grid.w);
        const h = Math.min(img.height / 3, clothingDetails.value.grid.h);

        const vectorHint = payload?.isVector ?? (typeof payload?.name === 'string' && payload.name.includes(':'));

        const newImage = {
          id: crypto.randomUUID?.() || Date.now().toString(),
          type: 'image',
          imgUrl: payload.imgUrl,
          img,
          showHandles: true,
          x: clothingDetails.value.grid.x + (clothingDetails.value.grid.w - w) / 2,
          y: clothingDetails.value.grid.y + (clothingDetails.value.grid.h - h) / 2,
          w,
          h,
          aspect: img.width / img.height,
          origW: img.width / 3,
          origH: img.height / 3,
          isSelected: true,
          z: zCounter.value++,
          rotation: 0,
          isVector: Boolean(vectorHint),
        } as ImageObject & Record<string, any>;

        if (payload?.name) {
          newImage.name = payload.name;
        }

        if (payload?.shapeMeta) {
          newImage.shapeMeta = payload.shapeMeta;
        }

        images.push(newImage);

        draw();
      };
    }

    if (type === 'text') {
      texts.forEach(t => t.isSelected = false);

      texts.push({
        id: crypto.randomUUID?.() || Date.now().toString(),
        type: 'text',
        content: typeof payload === 'string' ? payload : payload.value || 'Sample Text',
        font: payload.font || 'Arial',
        color: payload.color || '#000000',
        outlineColor: payload.outlineColor || 'None',
        outlineWidth: payload.outlineWidth || 2,
        showHandles: true,
        size: payload.size || 1,
        alignment: payload.alignment || 'left',
        rotation: payload.rotation || 0,
        x: clothingDetails.value.grid.x + 30,
        y: clothingDetails.value.grid.y + 100,
        w: clothingDetails.value.grid.w - 40,
        h: 60,
        isSelected: true,
        z: zCounter.value++,
        // 👇 NEW
        effect: { name: 'none', options: withDefaults('none') },
      });

      draw();
    }
  }
  /**
   * Applies a new garment definition and refreshes dependent state (grid, previews, bg).
   */
  function updateClothing(details: any) {
    if (!details) return;

    const colorsArray = Array.isArray(details.colors) ? details.colors : [];
    const primaryColor = colorsArray[0] ?? {};
    const bg = typeof primaryColor?.background === 'string' ? primaryColor.background : undefined;
    const backgroundChange = Boolean(details.front || details.back || bg);
    const incomingGrid = details.grid as DesignGrid | undefined;

    if (incomingGrid) {
      clothingDetails.value.grid = {
        ...resolveGrid(),
        ...incomingGrid,
      } as DesignGrid;
    } else {
      clothingDetails.value.grid = { ...DEFAULT_GRID };
    }

    requestAutoGrid(!backgroundChange);

    if (Object.prototype.hasOwnProperty.call(details, 'sizeMeasurements')) {
      clothingDetails.value.sizeMeasurements = hydrateSizeMeasurements(details.sizeMeasurements);
    }

    if (Object.prototype.hasOwnProperty.call(details, 'size')) {
      clothingDetails.value.size = typeof details.size === 'string' ? details.size : '';
    }

    const assignableKeys: Array<keyof typeof clothingDetails.value> = ['name', 'image', 'style', 'gender'];
    for (const key of assignableKeys) {
      if (Object.prototype.hasOwnProperty.call(details, key) && details[key] !== undefined) {
        (clothingDetails.value as any)[key] = details[key];
      }
    }

    if (backgroundChange) {
      if (details.front) viewToSrc.Front = details.front;
      if (details.back) {
        viewToSrc.Back = details.back;
      } else if (details.front) {
        viewToSrc.Back = details.front;
      }
      if (!details.front && !details.back && bg) {
        viewToSrc.Front = bg;
        viewToSrc.Back = bg;
      }
    }

    if (!backgroundChange && bg) {
      viewToSrc.Front = viewToSrc.Front || bg;
      viewToSrc.Back = viewToSrc.Back || bg;
    }

    if (!viewToSrc.Back) {
      viewToSrc.Back = viewToSrc.Front || '';
    }

    viewMirrored.Front = false;
    viewMirrored.Back = false;

    refreshAllPreviews();

    if (details.bgTransform) {
      setBackgroundTransform(details.bgTransform);
    }

    requestMeasurementRefresh();

    resetDesignState('Front');
    setShirtBackground(viewToSrc.Front || viewToSrc.Back || '', { mirror: viewMirrored.Front });
    draw();
  }

  /**
   * Resets the designer to its initial empty state.
   */
  function clearClothing() {
    resetClothingDetails();
    viewToSrc.Front = '';
    viewToSrc.Back = '';
    viewMirrored.Front = false;
    viewMirrored.Back = false;
    resetDesignState('Front');
    setShirtBackground('', { mirror: false });
    refreshAllPreviews();
    draw();
  }

  /**
   * Updates garment imagery from the outside world without altering other state.
   */
  function setClothingImages(imgs: { front?: string; back?: string; side?: string }) {
    if (imgs.front) viewToSrc.Front = imgs.front;
    if (imgs.back) {
      viewToSrc.Back = imgs.back;
    } else if (imgs.front) {
      viewToSrc.Back = imgs.front;
    }
    if (!viewToSrc.Back) {
      viewToSrc.Back = viewToSrc.Front || '';
    }
    viewMirrored.Front = false;
    viewMirrored.Back = false;
    requestAutoGrid();
    setShirtBackground(viewToSrc[selectedView.value] || viewToSrc.Front || '', { mirror: viewMirrored[selectedView.value] });
    refreshAllPreviews();
    draw();
  }

  // -----------------------------------------------------
  // Lifecycle & Watchers
  // -----------------------------------------------------

  onMounted(() => {
    storeViewState(selectedView.value);
    updatePreviewFor(selectedView.value, { skipBackground: !shirtBgLoaded.value });
    loadViewState(selectedView.value);
    setShirtBackground(viewToSrc[selectedView.value] || viewToSrc.Front || '', { mirror: viewMirrored[selectedView.value] });
    refreshAllPreviews();
    window.addEventListener('shirtlab-selectClothing', clothingSelectionHandler);
  });

  onUnmounted(() => {
    window.removeEventListener('shirtlab-selectClothing', clothingSelectionHandler);
  });

  watch(showGrid, () => {
    draw();
  });

  watch(() => clothingDetails.value.grid, () => {
    draw();
  }, { deep: true });

  watch(() => clothingDetails.value.size, () => {
    requestMeasurementRefresh();
  });

  watch(() => clothingDetails.value.sizeMeasurements, () => {
    requestMeasurementRefresh();
  }, { deep: true });

  watch(() => props.clothing, (details) => {
    if (details) {
      updateClothing(details);
    } else {
      clearClothing();
    }
  }, { immediate: true, deep: true });

  watch(selectedObject, (next) => {
    if (!next) return;
    const mirror = texts.find(txt => txt.id === next.id);
    if (mirror) {
      Object.assign(mirror, next);
      draw();
    }
  }, { deep: true });

  defineExpose({
    openFileDialog,
    updateClothing,
    setClothingImages,
    setBackgroundTransform,
    uploadObject,
    selectedObject,
    draw,
    centerSelectedText,
    duplicateSelectedText,
    bringSelectedForward,
    sendSelectedBack,
    clearClothing,
  });


</script>

<style scoped lang="scss">

  .page {
    display: flex;
  }

  .lab-container {
    left: 40%;
  }

  .lab-container canvas {
    border: 2px solid #d1d5db;
    border-radius: 1.5rem;
    background-color: #ffffff;
    box-shadow: 0 12px 28px rgba(15, 23, 42, 0.12);
  }

  * {
    user-select: none;
  }

  .canvas {
    position: absolute;
    z-index: 0;
    background: #fff;
    border-radius: 2rem;
    padding: 6px;
    width: 1rem;
    height: 1rem;
    line-height: 0.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
    transform: translate(-50%, -50%);
  }

  .sidebar {
    position: absolute;
    top: 1;
    right: 0rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 0.6rem;
    width: auto;
    height: auto;

    span {
      background-color: rgb(255, 255, 255);
      padding: 0.3rem;
      font-family: 'Anek Latin';
      font-size: 0.7rem;
      font-weight: 300;
      border-radius: 0.5rem;
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
      margin: 0 auto;

    }

    img {
      object-fit: contain;
      width: 2rem;
      margin: 0 auto;
      padding-right: 5px;
    }

    input {
      cursor: pointer;
      object-fit: contain;
      background: linear-gradient(180deg, #ffffff, #f6f8fb);
      padding: 0.3rem 0.5rem;
      font-family: 'Anek Latin';
      font-size: 0.7rem;
      font-weight: 300;
      border-radius: 0.5rem;
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
      margin: 0 auto;
      color: black;
      width: 100%;
      height: 100%;
      border: none;
      position: relative;
      /* for ripple */
      overflow: hidden;
      /* clip ripple */
      will-change: transform, box-shadow, background;
      transform-origin: center;
      transition: transform 140ms ease, box-shadow 200ms ease, background 220ms ease;
      box-shadow: 0 0 0 rgba(0, 0, 0, 0);

      /* subtle hover lift */
      &:hover {
        transform: translateY(-1px);
        box-shadow: 0 6px 16px rgba(0, 0, 0, 0.08);
        background: linear-gradient(180deg, #ffffff, #eef2f7);
      }

      /* press state with ripple */
      &:active {
        transform: translateY(0) scale(0.98);
      }

      /* center ripple */
      &::after {
        content: "";
        position: absolute;
        left: 50%;
        top: 50%;
        width: 10px;
        height: 10px;
        border-radius: 50%;
        background: rgba(167, 197, 102, 0.35);
        /* matches green accent */
        transform: translate(-50%, -50%) scale(0);
        opacity: 0;
        pointer-events: none;
      }

      &:active::after {
        animation: ripple 420ms ease-out;
      }
    }

  }


  @keyframes ripple {
    0% {
      transform: translate(-50%, -50%) scale(0);
      opacity: 0.35;
    }

    60% {
      transform: translate(-50%, -50%) scale(14);
      opacity: 0.18;
    }

    100% {
      transform: translate(-50%, -50%) scale(18);
      opacity: 0;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .sidebar input {
      transition: none;
    }

    .sidebar input:active {
      transform: none;
    }

    .sidebar input::after {
      animation: none !important;
    }
  }

  .viewport-frame {
    background-color: rgb(255, 255, 255);
    border-radius: 0.75rem;
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    padding: 0.75rem;
  }

  /* Target any SVG inside a handle button */
  .canvas :deep(svg) {
    fill: rgb(167, 197, 102);
    /* green */
    stroke: rgb(167, 197, 102);
  }


</style>
