import type { ColorOption } from '../../shirtlab/types';

export const COLOR_OPTIONS: Record<string, ColorOption> = {
    'None': { name: 'none', color: '#00000001' },
    'White': { name: 'White', color: '#ffffffff' },
    'Black': { name: 'Black', color: '#000000ff' },

    'Gray': { name: 'Gray', color: '#6f7372' },
    'Light Gray': { name: 'Light Gray', color: '#979697' },
    'Purple Pink': { name: 'Purple Pink', color: '#cd629b' },
    'Hot Pink': { name: 'Hot Pink', color: '#ee529b' },
    'Light Pink': { name: 'Light Pink', color: '#f190b2' },
    'Dark Pink': { name: 'Dark Pink', color: '#c75994' },
    'Wine Purple': { name: 'Wine Purple', color: '#883152' },
    'Dark Wine Red': { name: 'Dark Wine Red', color: '#831e33' },
    'Crimson': { name: 'Crimson', color: '#b11a2a' },
    'Scarlet Red': { name: 'Scarlet Red', color: '#c11c29' },
    'Bright Red': { name: 'Bright Red', color: '#e83235' },
    'Orange Red': { name: 'Orange Red', color: '#ee5625' },
    'Bright Orange': { name: 'Bright Orange', color: '#f58c29' },
    'Yellow Orange': { name: 'Yellow Orange', color: '#fbb531' },
    'Bright Yellow': { name: 'Bright Yellow', color: '#fbcd32' },
    'Brown Yellow': { name: 'Brown Yellow', color: '#bd9e2c' },
    'Light Sage': { name: 'Light Sage', color: '#929f72' },
    'Lime Green': { name: 'Lime Green', color: '#9fce6d' },
    'Grass Green': { name: 'Grass Green', color: '#60af44' },
    'Forest Green': { name: 'Forest Green', color: '#23753c' },
    'Dark Green': { name: 'Dark Green', color: '#265132' },
    'Deep Green': { name: 'Deep Green', color: '#2c4b31' },
    'Teal': { name: 'Teal', color: '#1e727b' },
    'Cyan Blue': { name: 'Cyan Blue', color: '#2f93b3' },
    'Sky Blue': { name: 'Sky Blue', color: '#5ca7d5' },
    'Steel Blue': { name: 'Steel Blue', color: '#6490bc' },
    'Royal Blue': { name: 'Royal Blue', color: '#2d5797' },
    'Dark Royal Blue': { name: 'Dark Royal Blue', color: '#284487' },
    'Navy Blue': { name: 'Navy Blue', color: '#193461' },
    'Lavender Gray': { name: 'Lavender Gray', color: '#645687' },
    'Orchid Purple': { name: 'Orchid Purple', color: '#9c4e99' },
    'Plum': { name: 'Plum', color: '#693082' },
    'Dark Plum': { name: 'Dark Plum', color: '#572365' },
    'Eggplant Purple': { name: 'Eggplant Purple', color: '#5b215c' },
    'Dark Brown': { name: 'Dark Brown', color: '#4d3523' },
    'Medium Brown': { name: 'Medium Brown', color: '#865636' },
    'Tan Brown': { name: 'Tan Brown', color: '#ac7950' },
    'Light Tan': { name: 'Light Tan', color: '#dda56e' },
    'Peach': { name: 'Peach', color: '#f0c187' },
    'Beige': { name: 'Beige', color: '#c9b894' }
};